import "../../globals.css";
import type { Metadata } from "next";
import Topbar from "@/presentation/pages/Dashboard/components/Topbar";
import LeftSidebar from "@/presentation/pages/Dashboard/components/LeftSidebar";
import Bottombar from "@/presentation/pages/Dashboard/components/Bottombar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Topbar />

      <main className="flex flex-row">
        <LeftSidebar />

        <section className="flex min-h-screen flex-1 flex-col items-center px-6 pb-10 pt-28 max-md:pb-32 sm:px-10">
          <div className="w-full max-w-4xl">{children}</div>
        </section>
      </main>

      <Bottombar />
    </>
  );
}
